### ISSUE TITLE
snpClust Problem while setting all > 1 to 1

### ISSUE THREAD

**Issue by lisiarend** [pneuvial/adjclust#82] opened 2024-07-30 13:52 UTC
Hello,

I have a problem while trying to cluster my LD (large dgCMatrix) with snpClust.

My input is a non-public data set, so I cannot hand over the data. But I ran the following steps:
`
h <- 5 
`
`
ld <- snpStats::ld(geno, stats = c("R.squared"), depth = h)
`

Resulting in ld being a Large dgCMatrix with dimensions 59087 x 59087.

Then I tried to cluster the matrix with snpClust:
`
fitH <- adjclust::snpClust(geno, h = h, stats = "R.squared")
`

And I am getting this error:
Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In run.snpClust(x, h = h, stats = stats) :
  Forcing the LD similarity to be smaller than or equal to 1
2: In int2i(as.integer(i), n) :
  NAs introduced by coercion to integer range

I already checked, the error occurs in line 12 of the function run.snpClust.

Can you help me? I don't know why this is line is making an error.

**Comment by tuxette** [comment] 2024-07-31 11:30
Hi @lisiarend ! Do you have any missing values in your matrix `ld`? I would advise that you first perform the checks on this matrix by yourself:
- Is the diagonal of  `ld` equal to 1?
- Do you have any values in `ld`outside $[0,1]$?
If the answers to all these questions are no, then try to directly use `adjclust` on `ld`. The result is meant to be equivalent to what you do with `snpClust`.

I am currently on vacation so my answers will probably be slow.

**Comment by pneuvial** [comment] 2024-08-30 12:10
Hi @lisiarend,

Have you been able to investigate the suggestions by @tuxette ?

Also, I understand that your data is not public, but maybe you could send us an anonymized version of a small subset of the data where you can reproduce the same problem?

**Comment by tuxette** [comment] 2024-10-08 08:43
No feedback so far so I am closing this issue because results can not be traced or reproduced.

**Closed by tuxette** 2024-10-08 08:43 UTC
